import type { Metadata } from "next";
import { Poppins, Space_Mono } from "next/font/google";
import "./globals.css";
import { StagewiseToolbar } from '@stagewise/toolbar-next';
import ReactPlugin from '@stagewise-plugins/react';
import StagewiseToolbarClient from '@/components/StagewiseToolbarClient';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400"],
  style: ["italic", "normal"],
  variable: "--font-space-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${spaceMono.variable} font-sans antialiased min-h-screen bg-primaryBackground relative overflow-x-hidden`}>
        {/* Video de fondo global */}
        <video
          autoPlay
          loop
          muted
          playsInline
          className="fixed inset-0 w-full h-full object-cover z-0"
          src="/videos/bubble-bg.mp4"
        />
        <div className="relative z-20 min-h-screen flex flex-col">
          {children}
          {/* Stagewise Toolbar only in dev, as a client component */}
          <StagewiseToolbarClient />
        </div>
      </body>
    </html>
  );
}
